version: '3.8'

services:
  backend:
    build:
      context: ./CookCookhNya-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./CookCookhNya-frontend
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN} # add your personolised token for local development in .env file in the same directory with compose.yml
      - API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
