services:
  backend:
    build:
      context: ./CookCookhNya-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      app-network:
        aliases:
          - backend 

  frontend:
    build:
      context: ./CookCookhNya-frontend
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      app-network:
        aliases:
          - frontend

networks:
  app-network:
    driver: bridge
