name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
    
      - name: Update submodules explicitly
        run: git submodule update --init --recursive
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: j0cos/cookcookhnya-backend:${{ github.sha }}
        
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./Frontend
          push: true
          tags: j0cos/cookcookhnya-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          BACKEND_TAG: ${{ github.sha }}
          FRONTEND_TAG: ${{ github.sha }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/app
            # Debug: Check environment variables
            echo "BACKEND_TAG=${{ github.sha }}"
            echo "FRONTEND_TAG=$FRONTEND_TAG"
            echo "BACKEND_TAG=${{ github.sha }}
            FRONTEND_TAG=${{ github.sha }}
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            API_URL=${{ secrets.API_URL }}" > /root/app/.env
            docker pull j0cos/cookcookhnya-backend:$BACKEND_TAG
            docker pull j0cos/cookcookhnya-frontend:$FRONTEND_TAG
            docker-compose -f /root/app/compose.yaml up -d
