name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test output
        run: echo "test gh actions"

